# Generated by Django 5.1.3 on 2024-11-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='review_score',
            field=models.FloatField(default=0.0),
        ),
    ]
