# Generated by Django 5.1.3 on 2024-11-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fog', '0002_alter_statistics_review_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='review_amount',
            field=models.IntegerField(default=0),
        ),
    ]
