# Generated by Django 5.1.3 on 2024-11-06 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fog', '0003_statistics_review_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statistics',
            options={'ordering': ['review_score'], 'verbose_name': 'Статистика', 'verbose_name_plural': 'Статистика'},
        ),
    ]
