# Generated by Django 5.1.3 on 2024-11-06 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fog', '0004_alter_statistics_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Оценка'),
        ),
    ]
