# Generated by Django 5.1.3 on 2024-11-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fog', '0005_alter_reviews_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='score',
            field=models.FloatField(blank=True, null=True, verbose_name='Оценка'),
        ),
    ]
