# Generated by Django 4.2.16 on 2024-11-07 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fog', '0006_alter_reviews_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Изображение'),
        ),
    ]
