# Generated by Django 4.2.16 on 2024-11-07 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fog', '0007_game_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_alpha',
            field=models.BooleanField(default=False, verbose_name='Альфа версия'),
        ),
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выхода'),
        ),
    ]
